name: Node build and test
on:
  workflow_call:
    inputs:
      install_node:
        type: boolean
      name:
        required: false
        type: string
      description:
        required: false
        type: string
      script:
        required: false
        type: string
        
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Cache NPM dependencies # we use actions/cache to cache the node_modules directory. We use the hash from the package-lock.json file as the key
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies # we only install dependencies if the cache is invalidated
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm ci
        env:
          CI: true

      - name: Test
        run: npm run test
        env:
          CI: true        
